### ISSUE TITLE
'Handles' not defined

### ISSUE THREAD

**Issue by TrackLab** [ditzel/SimpleIK#2]
I would have forked the Project to fix the Error myself, but my Unity C# Skills are not advanced enough for that.

The Script works great. But when exporting the Game, Unity throws an Error.

No matter if I actually use the Scripts, or not. As long as FastIK is imported, building the Game results in this Error:

> Assets\FastIK\Scripts\FastIK\FastIKFabric.cs(197,17): error CS0103: The name 'Handles' does not exist in the current context

I checked the File myself, from what I`ve seen you didn`t defined 'Handles'

**Comment by dradb** [comment]
I have the same issue as Track Lab.

**Comment by ditzel** [comment]
Sorry. Just comment out the OnDrawGizmos.
The latest version fixes this issue
