### ISSUE TITLE
[Bug] Not able to build, because of wrong region set in FastIKFabric

### ISSUE THREAD

**Issue by FireDragonGameStudio** [ditzel/SimpleIK#6]
```
void OnDrawGizmos()
{
#if UNITY_EDITOR
......
}
```

As mentioned in #3 this error will result in an Build error. You'll have to move the region either over the `OnDrawGizmos` or within the Method. It's still not fixed in the AssetStore version.

Can you update it?

Best regards :)

**Comment by ditzel** [comment]
Will be released in Version 1.2
